### PR TITLE
Fixed plugin bug in Xcode 16.3 beta

### LINKED ISSUE #56: Build fails with Xcode 16.3 beta: "SourcePackages not found"
Running the LicenseList build plugin fails when we build our app with Xcode 16.3 beta

Image

The `~/Library/Developer/Xcode/appname-drq...vcx/SourcePackages` folder does exist.
Anyone else seeing this problem?

### PR DESCRIPTION
**Pull request by Kyome22**
close #56 
There was a specification change to pluginWorkDirectory in Xcode 16.3 beta.
Fixed the plugin to resolve SourcePackages file paths in both Xcode 16.2 and earlier and 16.3 beta.

### CODE REVIEW

File: Plugins/PrepareLicenseList/main.swift [hunk 1]
```diff
@@ -3,18 +3,20 @@ import PackagePlugin
...
-        while tmpURL.lastPathComponent != "SourcePackages" {
-            tmpURL = tmpURL.deletingLastPathComponent()
+
+        var tmpURL = pluginWorkDirectory
+        while tmpURL.deletingLastPathComponent().lastPathComponent != "DerivedData" {
+            tmpURL.deleteLastPathComponent()
         }
+        tmpURL.append(path: "SourcePackages")
         return tmpURL
     }
```
Comment (ichiho-ojima) [inline Plugins/PrepareLicenseList/main.swift:21]: I believe the following code can achieve equivalent results while avoiding a while statement.

```swift
func sourcePackages(_ pluginWorkDirectory: URL) throws -> URL {
    let pluginWorkDirectoryPath = pluginWorkDirectory.absoluteURL.path()
    guard let range = pluginWorkDirectoryPath.range(of: "/DerivedData/") else {
        throw DerivedDataNotFoundError()
    }

    let derivedDataDirectoryPath = String(pluginWorkDirectoryPath.prefix(upTo: range.upperBound))
    let sourcePackagesPath = derivedDataDirectoryPath + "SourcePackages"
    return URL(filePath: sourcePackagesPath)
}
```

Comment (Kyome22) [reply Plugins/PrepareLicenseList/main.swift:21]: I think this implementation is simple.
However, there is a danger that anything can be done when manipulating character strings, so I intentionally wrote it so that it can be manipulated within the URL category.

Comment (ichiho-ojima) [reply Plugins/PrepareLicenseList/main.swift:21]: Thank you for explaining your implementation intent.

Indeed, converting to String without unit tests could be risky.
Would it be difficult to add unit tests for this method? For example, could we extract this method into a separate target and import it into this plugin?

On a slightly different note, if you prefer an implementation based on `URL`, perhaps a guard statement like this might fit better (though it still involves string conversion):
```swift
guard pluginWorkDirectory.pathComponents.contains("/DerivedData/")
```

Comment (ichiho-ojima) [reply Plugins/PrepareLicenseList/main.swift:21]: Thank you for your detailed investigation.
It seems difficult to test with the current structure due to SPM's functional constraints.

We could refactor by consolidating as much logic as possible in the executableTarget side and just calling it from the plugin, which would allow us to test the important logic parts, but that would be beyond the scope of this PR.

**Review by ichiho-ojima — APPROVED** [review]
LGTM
